// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package ru.grpc.simple.proto;

public interface LogoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LogoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
